Repository Mirantis/kqueen, pull requests merged in 2018-06, with the labels that each got.

#274 Minor, suggested travis spec. update
  .travis.yml
Labels: P3 - nice to have

#328 Hotfix for avoid travis issues
  setup.py
Labels: P1 - top, bug

#295 OpenStack kubespray engine
  .gitignore
  Dockerfile
  MANIFEST.in
  docs/kqueen.engines.rst
  kqueen/config/base.py
  kqueen/engines/__init__.py
  kqueen/engines/openstack_kubespray.py
  kqueen/server.py
  setup.py
Labels: P1 - top
